### ISSUE TITLE
source code of demos

### ISSUE THREAD

**Issue by severak** [DJMaster/cairo-fpc#1]
can I have source code of demos?

**Comment by DJMaster** [comment]
Thank you severak for your interest. Source code of demos will be published on the website soon. Are you interested to a specific demo?

**Comment by severak** [comment]
cairo clock is enough for me

**Comment by DJMaster** [comment]
Clock demo source code published: http://www.djmaster.com/freepascal/demos/clock.php

Consider it an initial release, some things must be tuned (paths, ico, etc.). Have fun!
